version: '3.0'

services:
    database:
        image: mysql:latest
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3309:3306"
        volumes:
            - my-datavolume:/var/lib/mysql
    app:
        build:
            args:
                user: parvej
                uid: 11009
            context: ./
            dockerfile: Dockerfile
        image: parvej-laravel-image
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    server:
        image: nginx
        container_name: server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/

volumes:
    my-datavolume:
        driver: local
